### PR TITLE
HTTP_PROXY support

### PR DESCRIPTION
**Pull request by darhelm**
In case the server is in iran or anywhere that telegram is possibly filtered with this feature Clients can use a http proxy to bypass the firewall

Changes:
- HTTP_PROXY prompt in bash file 
- check if HTTP_PROXY in config.py is not null, if null create Bot instance normally, otherwise process the proxy url and pass it's parameters seperately to Request and pass the Request instance to the Bot instance to use http proxy

### CODE REVIEW

**Review by erfjab — APPROVED** [review]
I couldn't test code, but I liked the idea.

**Review by XuVix — CHANGES_REQUESTED** [review]
It's a good idea, but there are easier ways to use a proxy.  I will add it.

**Comment by XuVix** [comment]
> I couldn't test code, but I liked the idea.

To test, I want to block Telegram in a server, create a proxy on another server, and test 😁

Do you think it is possible?🤔

**Comment by erfjab** [comment]
> > I couldn't test code, but I liked the idea.
> 
> To test, I want to block Telegram in a server, create a proxy on another server, and test 😁
> 
> Do you think it is possible?🤔
> 
> 

It is better to test through Iran's server.

**Comment by darhelm** [comment]
> > > I couldn't test code, but I liked the idea.
> > 
> > 
> > To test, I want to block Telegram in a server, create a proxy on another server, and test 😁
> > Do you think it is possible?🤔
> 
> It is better to test through Iran's server.

i basically added this to work on iranian servers, also the telegram module the project uses was out dated so i had to work around that

**Comment by XuVix** [comment]
> > > > I couldn't test code, but I liked the idea.
> > > 
> > > 
> > > To test, I want to block Telegram in a server, create a proxy on another server, and test 😁
> > > Do you think it is possible?🤔
> > 
> > 
> > It is better to test through Iran's server.
> 
> i basically added this to work on iranian servers, also the telegram module the project uses was out dated so i had to work around that


Have you tested it completely?  Do you also have a tutorial on how to create a proxy?

**Comment by darhelm** [comment]
> > > > > I couldn't test code, but I liked the idea.
> > > > 
> > > > 
> > > > To test, I want to block Telegram in a server, create a proxy on another server, and test 😁
> > > > Do you think it is possible?🤔
> > > 
> > > 
> > > It is better to test through Iran's server.
> > 
> > 
> > i basically added this to work on iranian servers, also the telegram module the project uses was out dated so i had to work around that
> 
> Have you tested it completely? Do you also have a tutorial on how to create a proxy?

yes i have on my local system in theory it should work on any server too, for proxy i used the http inbound nekoray generates, in case you want to know more about the inbound: [http_proxy](https://www.v2ray.com/en/configuration/protocols/http.html)
some third party panels on servers allow the creation of such inbounds if you are not using a panel you can install the core itself and configure it's config.json to use the inbound and pass freedom as the object of outbound and if you are not using something like v2ray you can use third party proxies too as long as they haven't been filtered.

p.s: should i close the pull request?

image
image
image

**Pull request merged**
